services:
  app:
    build: .  # Diretório onde está o Dockerfile
    container_name: gerenciador-tarefas
    ports:
      - "8080:8080"  # Expondo a porta 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkpj856ubrc73fsh2fg-a.oregon-postgres.render.com:5432/gerenciador_tarefas_uppv
      SPRING_DATASOURCE_USERNAME: gerenciador_tarefas_uppv_user
      SPRING_DATASOURCE_PASSWORD: 4Qu0SBSmWWdeJJItMiBVbkrnc0fYeRPr
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Usando a rede padrão
